export const mediaSlots = [
  {
    id: "logo",
    label: "لوغو Kavaroc (SVG)",
    description: "لوغو البراند ديالك. استعمل SVG باش يبقى حاد فكل المقاسات. يبين في الـ Header و Footer.",
    type: "image",
    accept: "image/svg+xml,image/*",
    maxSizeMB: 2,
  },
  {
    id: "hero-main",
    label: "صورة المنتج الرئيسية",
    description: "تظهر في الـ Hero (مقاس مربع 1:1)",
    type: "image",
    accept: "image/*",
    maxSizeMB: 5,
  },
  {
    id: "hero-video",
    label: "فيديو المنتج",
    description: "فيديو ترويجي قصير يظهر تحت صورة المنتج",
    type: "video",
    accept: "video/*",
    maxSizeMB: 50,
  },
  {
    id: "gallery-1",
    label: "صورة المعرض 1 — العازل مركّب",
    description: "صورة العازل مركّب على الباب (مقاس 1:1)",
    type: "image",
    accept: "image/*",
    maxSizeMB: 5,
  },
  {
    id: "gallery-2",
    label: "صورة المعرض 2 — المنتج",
    description: "صورة واضحة للمنتج (مقاس 1:1)",
    type: "image",
    accept: "image/*",
    maxSizeMB: 5,
  },
  {
    id: "gallery-3",
    label: "صورة المعرض 3 — تفاصيل",
    description: "تفاصيل أو مميزات المنتج (مقاس 1:1)",
    type: "image",
    accept: "image/*",
    maxSizeMB: 5,
  },
  {
    id: "gallery-4",
    label: "صورة المعرض 4 — إضافية",
    description: "صورة إضافية (مقاس 1:1)",
    type: "image",
    accept: "image/*",
    maxSizeMB: 5,
  },
  {
    id: "solution-result",
    label: "صورة النتيجة",
    description: "صورة المنتج مركّب على الباب (مقاس 4:3)",
    type: "image",
    accept: "image/*",
    maxSizeMB: 5,
  },
  {
    id: "how-it-works",
    label: "صورة كيفاش كيخدم",
    description: "صورة توضح 3 خطوات التركيب (مقاس 4:3 أو أعرض)",
    type: "image",
    accept: "image/*",
    maxSizeMB: 5,
  },
  {
    id: "washable",
    label: "صورة القابلية للغسل",
    description: "صورة المنتج في آلة الغسيل أو صور توضيحية (مقاس 4:3)",
    type: "image",
    accept: "image/*",
    maxSizeMB: 5,
  },
];
